#ifndef CONTROLLER_PINOUT_H
#define CONTROLLER_PINOUT_H

#define JOYSTICK1_X_PIN 1
#define JOYSTICK1_Y_PIN 2
#define JOYSTICK2_X_PIN 4
#define JOYSTICK2_Y_PIN 5
#define BUTTON_L_PIN 16
#define BUTTON_R_PIN 39
#define TFT_CS_PIN 12
#define TFT_DC_PIN 13

#endif // CONTROLLER_PINOUT_H
